# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "0x1337: The Hacking Club"
email: hacking.club@students.iiit.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  We are a club based on ethical hacking, where we try to familiarize people with
  different tools and ways of ethical hacking and make them aware about how 
  cybersecurity is so important in today's world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - TODO.md
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock


# From template
# Team names, titles and social links
people:
- name: Muhammed Shamil K
  pic: 1
  position: Coordinator, Challenger

- name: Hardik Mittal
  pic: 1
  position: Coordinator, Challenger

- name: Monish Singhal
  pic: 1
  position: Coordinator, Challenger

- name: Anirudh Vempati
  pic: 1
  position: Coordinator, Challenger

- name: Kommireddy Bhargav Srinivas
  pic: 1
  position: Organizing Team Member

- name: Amey Karan
  pic: 1
  position: Challenger

- name: Gaurav Bahera
  pic: 1
  position: Challenger

- name: Kotekal Methukula Santhosh
  pic: 1
  position: Challenger

- name: Patel Umang Arvindbhai
  pic: 1
  position: Challenger

- name: Ankith Raghupathi Pai
  pic: 1
  position: Technical Team Member

- name: Himanshu Yadav
  pic: 1
  position: Technical Team Member

- name: Srijan Chakraborty
  pic: 1
  position: Technical Team Member

- name: Rohit Varma Chiluvuri
  pic: 1
  position: Designer

- name: Kriti Gupta
  pic: 1
  position: Designer

- name: Joshi Swarang Sarang
  pic: 1
  position: Content Writer

- name: Garima Tripathi
  pic: 1
  position: Content Writer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/0x1337iiith
  - title: facebook
    url: https://www.facebook.com/groups/hackingclubiiith
  - title: youtube
    url: https://www.youtube.com/channel/UCh8mysep91D52uOW47jN91A
  - title: instagram
    url: https://www.instagram.com/0x1337iiith/
  - title: discord
    url: https://discord.gg/xhDnu6Rnfh

# Build settings
markdown: kramdown
permalink: pretty
